# Generated by Django 5.0.8 on 2024-09-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_special_offer",
            field=models.BooleanField(default=False),
        ),
    ]
