# Generated by Django 5.0.8 on 2024-09-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecom", "0002_product_is_special_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
